"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 23:53:03.543591
"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('postback_secret', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('channels',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subscribers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bot_permissions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('profile_summary', sa.Text(), nullable=True),
    sa.Column('profile_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_channels_owner_user_id'), 'channels', ['owner_user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_run_at', 'jobs', ['status', 'run_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('mid', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('is_our_ad', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('skip_reason', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid')
    )
    op.create_index('ix_posts_chat_created', 'posts', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_text_hash'), 'posts', ['text_hash'], unique=False)
    op.create_table('processed_updates',
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dedupe_key')
    )
    op.create_table('users',
    sa.Column('max_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('max_user_id')
    )
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('erid', sa.String(length=64), nullable=False),
    sa.Column('pricing_model', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('budget_left', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('targeting', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_ads_category'), 'ads', ['category'], unique=False)
    op.create_index('ix_ads_embedding_hnsw', 'ads', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('channel_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_categories', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('allowed_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('allow_regulated', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('min_posts_between_ads', sa.Integer(), server_default='3', nullable=False),
    sa.Column('min_minutes_between_ads', sa.Integer(), server_default='120', nullable=False),
    sa.Column('max_ads_per_day', sa.Integer(), server_default='3', nullable=False),
    sa.Column('publish_delay_min', sa.Integer(), server_default='10', nullable=False),
    sa.Column('ad_ttl_hours', sa.Integer(), server_default='48', nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['channels.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.max_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_payout', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_message_mid', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_chat_status', 'proposals', ['chat_id', 'status'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('mid', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid'),
    sa.UniqueConstraint('proposal_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_placements_chat_id'), 'placements', ['chat_id'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('click_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('ua_hash', sa.String(length=64), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('click_id')
    )
    op.create_index('ix_clicks_dedupe', 'clicks', ['placement_id', 'ip_hash', 'ts'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('ref', sa.String(length=128), nullable=False),
    sa.Column('advertiser_debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('channel_credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_index(op.f('ix_ledger_entries_chat_id'), 'ledger_entries', ['chat_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_placement_id'), 'ledger_entries', ['placement_id'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('click_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['click_id'], ['clicks.click_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('click_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversions')
    op.drop_index(op.f('ix_ledger_entries_placement_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_chat_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_clicks_dedupe', table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_placements_chat_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index('ix_proposals_chat_status', table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('consents')
    op.drop_table('channel_settings')
    op.drop_index('ix_ads_embedding_hnsw', table_name='ads', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_ads_category'), table_name='ads')
    op.drop_table('ads')
    op.drop_table('users')
    op.drop_table('processed_updates')
    op.drop_index(op.f('ix_posts_text_hash'), table_name='posts')
    op.drop_index('ix_posts_chat_created', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_jobs_status_run_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_channels_owner_user_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
